Map<String, String> handSignMap = {
  "assets/signs/A.png": "A",
  "assets/signs/B.png": "B",
  "assets/signs/C.png": "C",
  "assets/signs/D.png": "D",
  "assets/signs/E.png": "E",
  "assets/signs/F.png": "F",
  "assets/signs/G.png": "G",
  "assets/signs/H.png": "H",
  "assets/signs/I.png": "I",
  "assets/signs/J.png": "J",
  "assets/signs/K.png": "K",
  "assets/signs/L.png": "L",
  "assets/signs/M.png": "M",
  "assets/signs/N.png": "N",
  "assets/signs/O.png": "P",
  "assets/signs/Q.png": "Q",
  "assets/signs/R.png": "R",
  "assets/signs/S.png": "S",
  "assets/signs/T.png": "T",
  "assets/signs/U.png": "U",
  "assets/signs/V.png": "V",
  "assets/signs/W.png": "W",
  "assets/signs/X.png": "X",
  "assets/signs/Y.png": "Y",
  "assets/signs/Z.png": "Z"
};
